version: '3.1'
services:
    sspanel:
        image: "baiyuetribe/sspanel:sspanel_type"
        restart: always
        container_name: sspanel
        networks:
            - frontend
            - backend
        ports:
          - de_port:80
        volumes:
          - /opt/sspanel/code:/sspanel
    mysql:
        image: "mysql:5.6"
        restart: always
        ports:
          - 3306:3306
        environment:
          TZ: 'Asia/Shanghai'
          MYSQL_DATABASE: sspanel
          MYSQL_ROOT_PASSWORD: sspanel
        volumes:
          - /opt/sspanel/mysql:/var/lib/mysql
          - /opt/sspanel/code/sql/glzjin_all.sql:/docker-entrypoint-initdb.d/sspanel.sql
        command: ['mysqld', '--character-set-server=utf8']     
        networks:
            - backend
        depends_on:
          - kodexplorer
    kodexplorer:
        image: baiyuetribe/kodexplorer
        restart: always
        ports:
          - 604:80
        volumes:
          - /opt/sspanel:/code
        networks:
          - backend
        depends_on:
          - sspanel           
networks:
    frontend:
    backend:
